name: med_tracking
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - pillow
  - xlsxwriter
  - lxml
  - atomicwrites
  - attrs
  - cffi
  - importlib_metadata
  - jinja2
  - markupsafe
  - more-itertools
  - packaging
  - pluggy
  - py
  - pycparser
  - pytest
  - simplegeneric
  - six
  - wcwidth
  - zipp
  - pip:
    - python-pptx
    - rpy2
